"""update model

Revision ID: b17d8861ed3b
Revises: e95651cfb5da
Create Date: 2023-10-27 12:39:23.928461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17d8861ed3b'
down_revision = 'e95651cfb5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=9), nullable=False))

    # ### end Alembic commands ###
